### ISSUE TITLE
Simplify hosts.yaml format

### ISSUE THREAD

**Issue by RandyLevensalor** [cablelabs/snaps-boot#253]
hosts.yaml is currently configured by task and not by compute node.

There are many duplicate entities required.

Have one yaml element for each server and only require a minimum of items are uniqure to each server, just as server name, IPs and MAC address.

Items that can be shared across servers, can be in a globals section.  Only list the dns server once.  If all servers have the same NIC layout, then that can be mapped in globals etc.

Allow for customizing individual servers.  The customization would have a priority over the global values.

**Comment by medberry** [comment]
You can also use group vars. Just keep it simple for manageability.

**Comment by willtome** [comment]
I would propose the following Ansible inventory compatible format. The required groups are `build`,`master`, and `minion`. These will be referenced by the Ansible playbooks. Host specific variables  `pxe_boot_mac` and `bmc_ip` are required for any system being booted via PXE. Variables can be assigned to either the `minion` group or the individual hosts to override default values. Any global values will reside in the `vars` section of the `all` group. This format will also enable to utilization for Ansible Vault for encryption of passwords or other sensitive data. 

```
---
build:
  hosts:
    localhost

master:
  hosts:
    master1:
      pxe_boot_mac: "ec:b1:d7:7f:5a:6c"
      bmc_ip: "10.197.124.22"
minion:
  hosts:
    minion1:
      pxe_boot_mac: "ec:b1:d7:7f:8a:9c"
      bmc_ip: "10.197.124.623"
    minion2:
      pxe_boot_mac: "ec:b1:d7:7f:4a:08"
      bmc_ip: "10.197.124.24"
      hugepagesz: "4M"
    minion3:
  vars:
    isolcpus: "0-20,1-22"
    hugepagesz: "2M"
    hugepages: "2048"


all:
  vars:
    digitalRebar:
      user: rocketskates
      password: r0cketsk8ts
    subnets:
      - subnet: management
        address: "10.197.121.0/24"
        name: Managment_SUBNET
        netmask: "255.255.255.0"
        range: "10.197.121.22 10.197.121.26"
        router: "10.197.121.1"
        default_interface: eno1
      - subnet: tenant
        address: "10.197.122.0/24"
        name: Tenant_SUBNET
        netmask: "255.255.255.0"
        range: "10.197.122.22 10.197.122.26"
        default_interface: eno2
      - subnet: public
        address: "10.197.123.0/24"
        name: Public_SUBNET
        netmask: "255.255.255.0"
        range: "10.197.123.22 10.197.123.26"
        router: "10.197.123.1"
        default_interface: eno3
    dn: cablelabs.com
    dns: "8.8.8.8"
    PROXY:
      ftp_proxy: ""
      http_proxy: ""
      https_proxy: ""
      #user to provide ngcacher_proxy only in case when servers are behind company
      #firewall, else left blank.
      ngcacher_proxy: ""
    PXE:
      bmc_user: admin
      bmc_password: foobarr
      pxe_server_ip: "10.197.121.21"
      pxe_server_interface: "ens3"
```
